### PR TITLE
add test for admin search

### PR DESCRIPTION
**Pull request by PetrDlouhy**
Test for #107

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
@adamcharnock I added a few more tests to try also filtering.
Should fail, if #107 was not fixed.

The tests are not passing, because `master` is broken.

**Comment by adamcharnock** [comment]
Whoops! I did not mean to add a number of those migrations, sorry about that. Checks are running now

**Comment by adamcharnock** [comment]
Ok, `master` should is fixed now. Merge as you wish.

**Comment by PetrDlouhy** [comment]
@adamcharnock OK, Merged.

**Pull request merged**
