### PR TITLE
allow set number of decimal_places in settings

### PR DESCRIPTION
**Pull request by PetrDlouhy**
I would like to set more decimal places in my project (because we want to transfer very little amounts of money). This adds possibility to set that in settings. Problem of my approach is, that user will need to set that before migrating (or create his own migration after setting that).

@adamcharnock What do you think about this? Do you see any better way? If not, I will write some note about this to docs before you merge it.

### CODE REVIEW

**Comment by adamcharnock** [comment]
Hey @PetrDlouhy, thank you for another PR! You raise a very good point here, I think this is something Hordak definitely needs to support.

My thoughts are:

1. The [forms](https://github.com/adamcharnock/django-hordak/tree/master/hordak/forms) will also need updated, search the source for `decimal_places=2`
2. This could also be a good time to consider adding a setting for the maximum currency value size too (i.e. `max_digits`, [docs](https://docs.djangoproject.com/en/2.1/ref/models/fields/#decimalfield)). This is particularly relevant for currencies such as YEN/WON which have larger values.
3. I cannot think of another sensible way to implement this, I think your settings-in-migration is probably the best approach.
4. When `decimal_places=3` I believe the currency will always render as `1.000`, rather than `1.00`. I think it is ok for Hordak to do this, as Hordak aims to provide core functionality rather than have opinions on rendering. I wanted to flag it here regardless though.

I therefore suggest:

- [ ] Update the forms
- [ ] Add a `HORDAK_MAX_DIGITS` settings, defaulting to the current value of `13`. The docs probably need to note that this includes the digits to the right of the decimal point, not just the left.
- [ ] Update the the settings docs. Note that changing these settings after first install will be tough.
- [ ] Update install docs to note that you should ensure the settings are correct.

Let me know if you don't have the time or inclination to do any of these and I'll be happy to take a look!

**Comment by PetrDlouhy** [comment]
@adamcharnock Everything done. Please review.

**Comment by adamcharnock** [comment]
Amazing, that was super-fast, thank you very much! 👍I'm going to merge now. I'll make a couple of tweaks myself then do a release.

**Comment by adamcharnock** [comment]
Hey @PetrDlouhy,

Just to update you on what I've done:

Looking at the code I realised that I had been ignoring the `hordak.defaults` module for a while, so I've moved the settings (and their associated defaults) into there. I've also updated the wording in the docs re the new settings. I hope that is ok with you.

I've also applied the black code formatter, so there have been some extensive but superficial changes there too. Probably worth pulling soon.

If it looks ok to you I'll do a release shortly.

Again, thank you very much for the pull request!

**Comment by PetrDlouhy** [comment]
@adamcharnock Everything is OK with me. Only, maybe it would be nice to mention the [MIGRATION_MODULES](https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-MIGRATION_MODULES) setting, which could be helpful in case of generating own migration.

**Comment by adamcharnock** [comment]
Done! Version `1.8.1` released 👍

**Pull request merged**
