### PR TITLE
Admin improvements

### PR DESCRIPTION
**Pull request by PetrDlouhy**
Few improvements to the admin interface

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
I have made even more improvements to the admin interface - sorting by balance and other columns.

The tests are not passing because `django-mptt` dropped support of `Python 3.4` - same test didn't pass on the `master` branch.

**Comment by adamcharnock** [comment]
Excellent, thank you @PetrDlouhy. Merging, sorry it took so long.

**Comment by adamcharnock** [comment]
Released in `1.9.0`.

**Comment by PetrDlouhy** [comment]
I just realized, that the sorting by columns through `admin_order_field`s doesn't work, because the `MPTTAdmin`. I use it with classical admin, because I don't have much tree structure in accounts.
I don't know, how to solve this with `MPTTAdmin`.

**Pull request merged**
