### PR TITLE
Django 2.1 compatability (child of #19)

### PR DESCRIPTION
**Pull request by p-baum**
Fix for #19 as request (I included the removal of the django version restriction - hope thats ok)

### CODE REVIEW

**Comment by p-baum** [comment]
I'm working on this...

**Comment by adamcharnock** [comment]
Thanks @p-baum, this looks great! I'm glad to have this fixed.

I've added a comment and applied the `black` code formatting tool (which I realise I should document the use of). Once Travis wakes up I'll be happy to merge.

**Comment by coler-j** [comment]
@adamcharnock are you going to merge this?

**Comment by coler-j** [comment]
@adamcharnock bump.

**Comment by adamcharnock** [comment]
Sorry for the delay everyone. This has now been merged as part of #42. Thank you very much @p-baum and @PetrDlouhy for working on this.

**Pull request closed without merging**
