### PR TITLE
chore: Changing Appconfig default_auto_field to BigAutoField

### PR DESCRIPTION
**Pull request by Lekhanshlkr**
changing the `id` field from `AutoField` to `BigAutoField` to support wide range of numeric id combinations

### CODE REVIEW

**Comment by kumarnmanoj** [comment]
@PetrDlouhy Please review this

**Comment by PetrDlouhy** [comment]
@Lekhanshlkr Generally looks good, thank you very much. Would you please look at the failed tests?

**Comment by Lekhanshlkr** [comment]
@PetrDlouhy I've applied `black` formatting to my code. The other issue was related to failing of the `mariadb` core in the `ci.yml`. Could you please look into it?

**Comment by PetrDlouhy** [comment]
@Lekhanshlkr I fixed the mariadb problem in `master` branch. Could you please rebase?

**Comment by Lekhanshlkr** [comment]
@PetrDlouhy There are still tests failing with MariaDB. Could you please look into it?

**Comment by PetrDlouhy** [comment]
@Lekhanshlkr I am not sure why this happens. The master branch now passes all tests, so it shouldn't be the issue.
The only thing I can think of is, that maybe the `parent_id` fields has stayed in the 32-bit format (weren't migrated) and that is causing the problems.

**Comment by adamcharnock** [comment]
Thank you for this @Lekhanshlkr! I recreated these changes locally and all the checks seemed to pass happily. I guess something got resolved since August. I'll close this PR, but your proposed changes have now been merged in #112.

**Pull request closed without merging**
