### PR TITLE
Check for missed migrations

### PR DESCRIPTION
**Pull request by pavel64-sutyrin**

### CODE REVIEW

**Comment by pavel64-sutyrin** [comment]
Yep, this check seems to give valuable feedback ;)

**Comment by adamcharnock** [comment]
Thanks @pavel64-sutyrin, this is a good check to do. Travis doesn't seem too happy though. I'm a bit busy right now, but if you can make travis happy I'll merge immediately.

**Comment by pavel64-sutyrin** [comment]
It's deeper than it seems. Django verisions have opinions on these transactions. Not urgent for me personally, but will definitely strenghten library for everyone)

**Comment by adamcharnock** [comment]
Hi Pavel,

I've merged this change in and put in place [a workaround](https://github.com/adamcharnock/django-hordak/commit/cbc31a3e34f9ac864bad183ec674ef90972a632b) to the 'breaks on some django versions' problem.

Travis seems happy now, and at least we'll now catch cases where migrations have not been created.

Thank you very much for the PR.

**Pull request closed without merging**
