### PR TITLE
Adding list of transactions and list of legs and moving footer to base.html

### PR DESCRIPTION
**Pull request by al1p-R**
Thank you for your great work !

### CODE REVIEW

**Comment by adamcharnock** [comment]
Hi @al1p-R, 

No problem! Thanks for the PR! I need to spend a moment looking into these changes, I'll try to get to it today or tomorrow. If you don't hear anything please do ping me.

My concern is that Hordak is billed as the model-layer for a double entry accounting platform, rather than a fully functioning UI. However, I have included a limited UI within Hordak to aid in getting up-and-running and (mostly) to aid in the creation of interfaces based on Hordak.

An example of such an interface is [Battlecat](https://github.com/adamcharnock/battlecat), which should really be the general purpose UI. It is currently pretty bare-bones.

This is what I'll be considering when I take a look.

Can I ask what you are making?

**Comment by al1p-R** [comment]
Understood, don't worry about it. Transaction list is just a view I used to better visualize what was happening with the tool. I thought it might help others.

**Comment by adamcharnock** [comment]
Merged! Thanks again for this. I made a few changes, in particular I'm showing the UUIDs rather than the IDs.

I was a little torn: I can see how having the IDs are useful for development, but I was also keen for these templates to be reusable in a non-development setting. However, upon thinking about it I realised this was probably unrealistic and the templates will most likely need to be customised in any eventuality. Given that, I compromised and displayed the UUIDs as they are there for display purposes (i.e. to avoid leaking the sequential IDs).

Separately, I've added a [current limitations](http://django-hordak.readthedocs.io/en/latest/#current-limitations) section in the docs which may be worth a read.

**Comment by al1p-R** [comment]
Thanks. This makes sense.

**Pull request merged**
